export const images = {
  ivPatient: "/images/ivPatient.webp",
  doctorOffice: "/images/doctorOffice.jpg",
  doctorConsultation: "/images/doctorConsultation.png",
  ivDrip: "/images/ivDrip.png",
  recliners: "/images/recliners.jpg",
  receptionLogo: "/images/receptionLogo.jpg",
  receptionDesk: "/images/receptionDesk.jpg",
  waitingArea: "/images/waitingArea.jpg",
  simulator: "/images/simulator.jpg",
  logo: "/images/logo.jpg",
  logoCircle: "/images/logoCircle.png",
  logoCircleLight: "/images/logoCircleLight.png",
  heroGenerated: "/images/heroGenerated.webp",
  wellnessResults: "/images/wellnessResults.webp",
  transformationSequence: "/images/transformationSequence.PNG",
  heroBackground: "/images/heroBackground.PNG",
  results1: "/images/results1.jpg",
  results2: "/images/results2.jpg",
  resultsMobile1: "/images/resultsMobile1.jpg",
  resultsMobile2: "/images/resultsMobile2.jpg",
  resultsTablet1: "/images/resultsTablet1.jpg",
  resultsTablet2: "/images/resultsTablet2.jpg",
  formBackground: "/images/formBackground.png",
  logoNav: "/images/logoNav.svg",
  logoFooter: "/images/logoFooter.png",
  favicon: "/images/favicon.ico"
};
